### ISSUE TITLE
genomespace_push errors if no URL

### ISSUE THREAD

**Issue by AndrewIsaac** [gvlproject/python-genomespaceclient#3]
From GenomeSpace (Aus)
Launching: "http://abrpi.genome.edu.au/galaxy/tool_runner?tool_id=genomespace_push"
as is (no files) gives error.
"Tool execution through the `tool_runner` requires a `runtool_btn` flag or `URL` parameter."

Want to launch Galaxy (and get login prompt if needed), and if files selected also do upload, else just home page.  Not sure if genomespace_push can do all this.

**Comment by nuwang** [comment]
The tool_runner is an internal part of Galaxy and its main job is to execute a given tool, with a given set of parameters, so without the parameters, it'll just throw up an error, which I think is reasonable behaviour. Perhaps the place to fix this is in GenomeSpace itself. Maybe a GenomeSpace tool can have two urls, instead of one, defined per tool. The first URL is the launch app url, and the second app is the execute tool url. What if you ask Ted or Marco, or maybe file a feature request in GenomeSpace?
