### ISSUE TITLE
Missing effectiveAcl information

### ISSUE THREAD

**Issue by MartinPaulo** [gvlproject/python-genomespaceclient#4]
The new release has lost the effectiveAcl information that used to be present in the old version. This information is very handy if you are trying to find out what folders a user can upload to.

**Comment by MartinPaulo** [comment]
I have fixed this on my checked out copy of the code. However, when I try to submit the pull request to this project, I get a 403 error.

**Comment by MartinPaulo** [comment]
So I've created a patch instead.
[Missing_effectiveAcl_information__4__The_GSFileMetadata_does_not_have_the_effectiveAcl_inf.patch.zip](https://github.com/gvlproject/python-genomespaceclient/files/939947/Missing_effectiveAcl_information__4__The_GSFileMetadata_does_not_have_the_effectiveAcl_inf.patch.zip)

I've run the tests against the Australian GenomeSpace backed by Swift. Sadly I don't have access to an AWS backing store.

**Comment by MartinPaulo** [comment]
BTW, I use this information when iterating across folders: if the user can't write to it, I don't show them the folder.

**Comment by nuwang** [comment]
@MartinPaulo Thanks for fixing this. I forgot to mention that I changed the list method to return a class instead of just the json dict - so that client code could be more compact, but I guess the effectiveACL attribute was overlooked. I don't know why you can't issue the pull request though - did you fork and then pull from the fork? Or attempt to push directly?

In any case, I've sent an invite with write access - so please let me know whether you still have trouble

**Comment by MartinPaulo** [comment]
I've updated the code with the missing ACL information and pushed the changes to the repository. The tests all pass when run against our local GenomeSpace backed by Swift. As mentioned, I'm not able to test against Amazon :(

**Comment by MartinPaulo** [comment]
Any ideas as to when this fix is going to be accepted/rejected/released? I need it for a project I'm working on :)  Thanks!

**Comment by MartinPaulo** [comment]
Code committed and accepted.
